name: Check broken link
on:
  schedule:
    - cron: '0 8 * * *'
  # Triggers the workflow on push or pull request events
  push:
    branches: [ main ]
    paths:
      - '**.md'
  pull_request:
    branches: [ main ]
    paths:
      - '**.md'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  LinkChecker:
    name: Link Checker
    #if: ${{ github.repository_owner == 'sandboxie-plus' }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
      actions: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4

      - name: Lychee Broken Link Checker
        id: lychee
        uses: lycheeverse/lychee-action@v1.9.3
        with:
          # Check all markdown files in repo
          args: -vvv --no-progress --max-redirects 30 --accept 200,429 './**/*.md'
          fail: true

      # To avoid automated spam, try to find an existing open issue before opening a new one
      # Source: https://github.com/cilium/tetragon/pull/805
      - name: Search for existing issue number
        id: search-issue
        if: ${{ !cancelled() }}
        run: |
          encoded_issue_name=$(echo "$ISSUE_NAME" | sed 's/ /%20/g')
          response=$(curl -s -X GET "https://api.github.com/search/issues?q=$encoded_issue_name+repo:isaak654/sandboxie-docs+state:open+label:automated-report&type=Issues")
          issue_number=$(echo "$response" | jq -r '.items[0].number // empty')
          echo "issue_number=$issue_number" >> $GITHUB_OUTPUT

      - name: Create issue from file
        if: ${{ !cancelled() && env.lychee_exit_code != 0 }}
        uses: peter-evans/create-issue-from-file@v5
        with:
          title: Link Checker Report
          content-filepath: ./lychee/out.md
          issue-number: ${{ steps.search-issue.outputs.issue_number }}
          labels: automated-report

  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.event.pull_request.head.ref }}
    - uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    - name: Install pre-commit
      shell: bash
      run: pip install --upgrade pip && pip install --upgrade pre-commit

    - name: Run pre-commit
      id: check
      shell: bash
      run: |
        pre-commit run --all-files

    - name: Commit changes
      if: ${{ !cancelled() && failure() }}
      shell: bash
      run: |
        git config --local user.name "pre-commit-ci[bot]"
        git config --local user.email "66853113+pre-commit-ci[bot]@users.noreply.github.com"
        git commit -m "[pre-commit.ci] pre-commit update" -a
        git pull --rebase --autostash && git push
        pre-commit clean
